replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.27-bookworm"

resources:
  limits:
    cpu: 50m
    memory: 128Mi
  requests:
    cpu: 30m
    memory: 128Mi